### ISSUE TITLE
Crash upon opening the C. Terminal ~ 1.20 (Fabric)

### ISSUE THREAD

**Issue by MaxingYT** [tom5454/Toms-Storage#270] opened 2023-07-20 21:15 UTC
The normal Terminal works fine, but when i´m trying to use the Crafting Terminal the game crashed and this is the following Crash-Code:

The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1729.method_30264()" because "this.field_3095" is null

**Comment by MaxingYT** [comment] 2023-07-20 21:40
Here is also the Crash-Log and the mods I´ve installed (must make a screenshot, it doesn´t let me send a rar file in this lol)

[crash-2023-07-20_23.26.20-client.txt](https://github.com/tom5454/Toms-Storage/files/12114216/crash-2023-07-20_23.26.20-client.txt)
![mods](https://github.com/tom5454/Toms-Storage/assets/98455498/641547cb-e9d4-4e52-8731-a34a4e2980de)

**Comment by tom5454** [comment] 2023-07-21 13:27
One of your mods breaks the recipe book, Apparently it's Visualoverhaul (https://github.com/tom5454/Toms-Storage/issues/251), but I can't see why.
Duplicate of #253

**Closed by tom5454** 2023-07-21 13:27 UTC
