### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by RazarJP** [tom5454/Toms-Storage#162] opened 2022-11-02 15:24 UTC
I'm running a server and one of my players make this following setup:

![2022-11-02_16 09 44](https://user-images.githubusercontent.com/93148116/199529161-eddd43ec-9497-4592-b452-bb07ceb943c2.png)
From top to bot, inventory connector - inventory proxy - cable connector and other side is just terminal - inventory connector - inventory proxy - cable connector
 
His actions by his own words: The thing that triggered the server crash was right clicking an inventory connector and then right clicking another that were connected with cables

And here the [Crash Report](https://github.com/tom5454/Toms-Storage/files/9921727/crash-2022-11-02_14.58.15-server.txt)

**Comment by tom5454** [comment] 2023-02-05 01:56
Duplicate of #178

**Closed by tom5454** 2023-02-05 01:56 UTC
