### ISSUE TITLE
(non-portable temrinals) (1.21 fabric) items flashing in and out of existence

### ISSUE THREAD

**Issue by ggezgaming** [tom5454/Toms-Storage#418] opened 2024-07-17 21:48 UTC
as the name suggests when looking at the terminal items will constantly flash in and out of existence as if the storage network was constantly being recognized and then forgotten. Minimizing amount of entities connected to the network fixes nothing.

**Comment by tom5454** [comment] 2024-07-18 18:26
Can you post a screenshot of your setup?

**Comment by tom5454** [comment] 2024-07-19 18:36
Duplicate of #420

**Closed by tom5454** 2024-07-19 18:36 UTC
