### ISSUE TITLE
 Crashing on Fabric server 1.20.1

### ISSUE THREAD

**Issue by p0nx77** [tom5454/Toms-Storage#346] opened 2024-04-14 02:35 UTC
Hi, I am running a fabric 1.20.1 server with a tons of mods, including Tom's version 1.6.6

Every time I open the advanced wireless terminal, go to the craft grid, open the book recipe, select any recipe, it crashes. I already updated everything.

the crash is only on the client-side, NOT on server side.

Here is the crash log:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-04-13 20:28:12
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at net.minecraft.class_514.handler$bgo000$brb$getOrderedRecipes(class_514.java:530)
	at net.minecraft.class_514.method_2639(class_514.java:113)
	at net.minecraft.class_514.method_48579(class_514.java:91)
	at net.minecraft.class_339.method_25394(class_339.java:78)
	at net.minecraft.class_513.method_2634(class_513.java:115)
	at net.minecraft.class_507.method_25394(class_507.java:291)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25394(CraftingTerminalScreen.java:129)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at net.minecraft.class_514.handler$bgo000$brb$getOrderedRecipes(class_514.java:530)
	at net.minecraft.class_514.method_2639(class_514.java:113)
	at net.minecraft.class_514.method_48579(class_514.java:91)
	at net.minecraft.class_339.method_25394(class_339.java:78)
	at net.minecraft.class_513.method_2634(class_513.java:115)
	at net.minecraft.class_507.method_25394(class_507.java:291)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25394(CraftingTerminalScreen.java:129)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: com.tom.storagemod.gui.CraftingTerminalScreen
	Mouse location: Scaled: (214, 195). Absolute: (856.000000, 782.000000)
	Screen size: Scaled: (640, 360). Absolute: (2560, 1440). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['davidoque'/189, l='ClientLevel', x=-780.45, y=184.00, z=2156.91]]
	Chunk stats: 1024, 828
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,92,16), Section: (at 0,12,0 in -4,5,1; chunk contains blocks -64,-64,16 to -49,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 12599136 game time, 13692668 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/JICKLUS.zip, file/FreshAnimations_v1.9.zip, file/FA+All_Extensions-v1.2.zip, presencefootsteps:default_sound_pack, Moonlight Mods Dynamic Assets, file/TZP_1.20.1_2.7.zip, minecraft:physicsmod, file/ReimaginedGUI(Dark) 1.20.zip, diagonalblocks:default_block_models

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2132479936 bytes (2033 MiB) / 4697620480 bytes (4480 MiB) up to 25333596160 bytes (24160 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-13700K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.42
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: Intel(R) UHD Graphics 770
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0xa780
	Graphics card #0 versionInfo: DriverVersion=31.0.101.5186
	Graphics card #1 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1e84
	Graphics card #1 versionInfo: DriverVersion=31.0.15.5161
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 53027.95
	Virtual memory used (MB): 25114.50
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 103.12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx24160m
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.2.1
		allarrowsinfinityfix: All Arrows Infinity Fix 1.4
		ambientsounds: AmbientSounds 5.3.8
		amendments: Amendments 1.20-1.1.11
			mixinsquared: MixinSquared 0.1.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20.1
		animated_guns: Simple Animated Guns 1.3
		another_furniture: Another Furniture 1.20.1-3.0.1
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		artifacts: Artifacts 9.4.3
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		asynclocator: Async Locator 1.3.0
		azurelib: AzureLib 2.0.20
		badoptimizations: BadOptimizations 1.6.3
		badpackets: Bad Packets 0.4.1
		bakery: Bakery 1.1.3
		balm-fabric: Balm 7.2.1
		beautify: Beautify 1.1.0+1.20
		bettercombat: Better Combat 1.8.3+1.20.1
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
			org_reflections_reflections: reflections 0.10.2
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterfpsdist: Better FPS distance Mod 1.20.1-4.0
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		blossom-back: BlossomBack 2.1.1+1.20
		blossom-homes: BlossomHomes 2.2.1+1.20
		blossom-lib: BlossomLib 2.5.4+1.20
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		bookshelf: Bookshelf 20.1.8
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		brb: Better Recipe Book 1.10.0+1.20.0-1
		bushierflowers: Bushier Flowers 0.0.3-1.20.1
		bwncr: Bad Wither No Cookie Reloaded 3.17.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		candlelight: Candlelight 1.2.8
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carrier: Carrier 1.12.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
		carryon: Carry On 2.1.2.7
		cavedust: Cave Dust 1.4.1
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		chimes: Chimes 2.0.1
		chunkloaders: Chunk Loaders 1.2.8+a
		chunky: Chunky 1.3.138
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.5.7
		collective: Collective 7.30
		compact_storage: Compact Storage 5.0.3_1.20.1
		continuity: Continuity 3.0.0-beta.4+1.20.1
		coroutil: CoroUtil 1.20.1-1.3.5
		cozy: Cozy 1.1.1
		craftingpad: Crafting Pad 1.0.12
		create: Create 0.5.1-f-build.1335+mc1.20.1
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.0+1.20.1
			porting_lib_base: Porting Lib Base 2.3.0+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.0+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.0+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.0+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.0+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.0+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.0+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.0+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.0+1.20.1
				porting_lib_common: Porting Lib Common 2.3.0+1.20.1
			porting_lib_models: Porting Lib Models 2.3.0+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.0+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.0+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.0+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.0+1.20.1
				porting_lib_core: Porting Lib Core 2.3.0+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.0+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		creativecore: CreativeCore 2.11.15
			net_minecraftforge_eventbus: eventbus 6.0.3
		cupboard: cupboard 1.20.1-2.2
		customvillagertrades: Custom Villager Trades 20.24.0
		diagonalfences: Diagonal Fences 8.1.3
			diagonalblocks: Diagonal Blocks 8.0.2
		doapi: Lets Do Api 1.2.8
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		dummmmmmy: MmmMmmMmmMmm 1.20-1.8.14
		dynmus: Dynamic Music 2.3.2+1.20
		easiervillagertrading: EasierVillagerTrading 1.20-fabric0.83.0-1.5.4
			gbfabrictools: GBfabrictools 1.3.5+1.20
		easyanvils: Easy Anvils 8.0.1
		elytraslot: Elytra Slot 6.3.0+1.20.1
		emojiful: Emojiful 4.2.0
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
			midnightlib: MidnightLib 1.1.0
		enchdesc: EnchantmentDescriptions 17.0.13
		endrem: End Remastered 5.2.4
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 1.3
		entity_texture_features: Entity Texture Features 5.2.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		equipmentcompare: Equipment Compare 1.3.8
		explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-hammers: Fabric Hammers 1.2.1
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		fallingtree: FallingTree 4.3.4
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		fastipping: Fast IP Ping 1.0.1
		ferritecore: FerriteCore 6.0.1
		filtpick: FiltPick 1.2.3
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		firstperson: FirstPerson 2.3.2
		forgeconfigapiport: Forge Config API Port 8.0.0
		geckolib: GeckoLib 4 4.4.2
			com_eliotlash_mclib_mclib: mclib 20
		getittogetherdrops: Get It Together, Drops! fabric-1.20-1.3.1
		hamsters: Hamsters 1.0.2-fabric
		handcrafted: Handcrafted 3.0.5
		healingcampfire: Healing Campfire 5.3
		highlighter: Highlighter 1.1.9
		iceberg: Iceberg 1.1.18
		immersive_aircraft: Immersive Aircraft 0.6.2+1.20.1
		indium: Indium 1.0.30+mc1.20.4
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemcollectors: Item Collectors 1.1.9
		jade: Jade 11.7.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		journeymap: Journeymap 5.9.18
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		jumpoverfences: Jump Over Fences 1.3.1
		knavesneeds: Knaves' Needs 2.0.1+1.20.1
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		lootbeams: LootBeams 1.0.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		luphieclutteredmod: Cluttered 2.1.0+1.20.1
		magnumtorch: Magnum Torch 8.0.2
		maxenchantx: Max Enchant X 1.3-1.20
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.1.0
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwroofs: Macaw's Roofs 2.2.4
		mcwwindows: Macaw's Windows 2.2.1
		mindfuldarkness: Mindful Darkness 8.0.0
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.12.1+mc1.20.1
		modmenu: Mod Menu 7.1.0
		moonlight: Moonlight 1.20-2.11.9
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		movingelevators: Moving Elevators 1.4.5
		mr_better_trees: Better Trees 1.7
		mru: Mineblock's Repeated Utilities 0.4.0+1.20
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		nightlights: Night Lights 1.1
		notenoughanimations: NotEnoughAnimations 1.7.0
		offlineskins: OfflineSkins 1.20.1-v1a-fabric
		owo: oωo 0.11.2+1.20
		paraglider: Paragliders 20.1.3
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		physicsmod: Physics Mod 3.0.13
		pickablevillagers: Pickable Villagers 1.4.5+1.20.1
		pickupnotifier: Pick Up Notifier 8.0.0
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.1+1.20.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		presencefootsteps: Presence Footsteps 1.9.1
			kirin: Kirin UI 1.15.4+1.20
		puzzleslib: Puzzles Lib 8.1.15
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		reinfbarrel: Reinforced Barrels 2.4.1+1.20
			reinfcore: Reinforced Core 3.1.2+1.20
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		right-click-harvest: Right-Click-Harvest 1.2.0
		roughlyenoughitems: Roughly Enough Items 12.0.697
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.9.0
		scarecrowsterritory: Scarecrows' Territory 1.1.11
		shouldersurfing: Shoulder Surfing Reloaded 2.8.1
		simplemagnets: Simple Magnets 1.1.10
		simplyswords: Simply Swords 1.54.0-1.20.1
		skinlayers3d: 3d-Skin-Layers 1.6.2
		smarterfarmers: Smarter Farmers 1.20-1.8.0
		smoothchunk: Smooth chunk save Mod 1.20.1-3.5
		smoothswapping: Smooth Swapping 0.9.3.1
		sodium: Sodium 0.5.8+mc1.20.1
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.3.1
		sounds: Sounds 0.6.0+1.20.1
			yet_another_config_lib_v3: YetAnotherConfigLib 3.2.2+1.20
				com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
				com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		structory: Structory 1.3.4
		structory_towers: Structory: Towers 1.0.6
		stylisheffects: Stylish Effects 8.0.0
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.20-2.8.4
		tectonic: Tectonic 2.2.1
		things: Things 0.3.3+1.20
			lavender: Lavender 0.1.0-pre.18+1.20
				lavender-md: lavender-md 0.1.0-pre.3+1.20
				lavender-md-owo-ui: lavender-md-owo-ui 0.1.0-pre.3+1.20
		toms_storage: Tom's Simple Storage Mod 1.6.6
		trade_cycling: Trade Cycling 1.20.1-1.0.7
		tradingpost: Trading Post 8.0.2
		trampledisablerfabric: Trample Disabler 1.0.8
		trashcans: Trash Cans 1.0.18
			team_reborn_energy: Energy 3.0.0
		trashslot: TrashSlot 15.1.0
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		trinkets: Trinkets 3.7.2
		universal-graves: Universal Graves 3.0.1+1.20.1
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.3+1.20.1
			polymer-core: Polymer (Core) 0.5.19+1.20.1
				polymer-networking: Polymer (Networking) 0.5.19+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.19+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.19+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.19+1.20.1
				polymer-common: Polymer (Common) 0.5.19+1.20.1
			predicate-api: Predicate API 0.2.1+1.20.1
			sgui: sgui 1.2.2+1.20
		universalenchants: Universal Enchants 8.0.0
			extensibleenums: Extensible Enums 7.0.1
		variantfurnaces: Variant Furnaces 1.2.0
		vinery: Vinery 1.4.7
		visuality: Visuality 0.7.0+1.20
		visualworkbench: Visual Workbench 8.0.0
		watut: What Are They Up To 1.20.1-1.0.12
		wi_zoom: WI Zoom 1.4-MC1.20.1
		xtraarrows: Xtra Arrows 3 3.0.4
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Loaded Shaderpack: ComplementaryReimagined_r5.2_dev8.zip
		Profile: Custom (+17 options changed by user)
	Flywheel Backend: Off
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.61, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/JICKLUS.zip, file/FreshAnimations_v1.9.zip, file/FA+All_Extensions-v1.2.zip, presencefootsteps:default_sound_pack, Moonlight Mods Dynamic Assets, file/TZP_1.20.1_2.7.zip, minecraft:physicsmod (incompatible), file/ReimaginedGUI(Dark) 1.20.zip
	Current Language: en_us
	CPU: 24x 13th Gen Intel(R) Core(TM) i7-13700K
	
	
	
Thanks,

**Comment by p0nx77** [comment] 2024-04-14 08:30
update: The mode "Better recipe book" was the problem. I removed and is no longer crashing.

**Comment by tom5454** [comment] 2024-04-14 14:06
Duplicate of #339

**Closed by tom5454** 2024-04-14 14:06 UTC
