### ISSUE TITLE
Toms-Storage and Druidcraft crates detection issues

### ISSUE THREAD

**Issue by DEX47** [tom5454/Toms-Storage#75] opened 2021-12-03 22:21 UTC
Minecraft 1.16.5
Forge 26.2.8
toms_storage-1.2.19
Druidcraft-1.16.5-0.4.54

The Druidcraft crates are a static chest 27 slot size container that can combine up to a 2x2 multi-block. Toms-Storage inventory connector is somehow getting a multiplier added when reading available crate slots depending on the multi-block configuration. This multiplier is also affecting the quantities of items displayed in your UI. The inventory cable connector is also not seeing the crate multi-block. It only sees the directly adjacent crate.

![2021-12-03_16 03 17](https://user-images.githubusercontent.com/8147134/144680431-6b8f2f22-cec9-48d3-bc0c-fe08146bd1ec.png)

![2021-12-03_16 04 16](https://user-images.githubusercontent.com/8147134/144680442-404ac3b2-d13b-4615-8609-ba7365c7fae9.png)

![2021-12-03_16 04 43](https://user-images.githubusercontent.com/8147134/144680456-1692427e-30f2-4cc3-b692-4f4eaaf5fa74.png)

![2021-12-03_16 05 05](https://user-images.githubusercontent.com/8147134/144680547-44caf279-75b3-48e2-b88c-92474f086a07.png)

**Comment by tom5454** [comment] 2022-02-09 13:28
Duplicate of #69

**Closed by tom5454** 2022-02-09 13:28 UTC
