### ISSUE TITLE
1.21.1 Breaking chest connected to system via cable connecter w/Inventory connector crashes

### ISSUE THREAD

**Issue by RC908** [tom5454/Toms-Storage#447] opened 2024-08-18 21:17 UTC
```
The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: 
Cannot invoke "net.fabricmc.fabric.api.lookup.v1.block.BlockApiCache.getWorld()" because "this.cache" is null
```
<details>
<summary>Full Report</summary>

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-08-18 17:12:17
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.lookup.v1.block.BlockApiCache.getWorld()" because "this.cache" is null
	at com.tom.storagemod.inventory.PlatformInventoryAccess$BlockInventoryAccess.get(PlatformInventoryAccess.java:63)
	at com.tom.storagemod.inventory.PlatformInventoryAccess$BlockInventoryAccess.getRootHandler(PlatformInventoryAccess.java:103)
	at com.tom.storagemod.inventory.MultiInventoryAccess.build(MultiInventoryAccess.java:52)
	at com.tom.storagemod.block.entity.InventoryConnectorBlockEntity.updateServer(InventoryConnectorBlockEntity.java:52)
	at com.tom.storagemod.util.TickerUtil.lambda$createTicker$1(TickerUtil.java:10)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:691)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:745)
	at net.minecraft.class_1937.method_18471(class_1937.java:488)
	at net.minecraft.class_3218.method_18765(class_3218.java:413)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.tom.storagemod.inventory.PlatformInventoryAccess$BlockInventoryAccess.get(PlatformInventoryAccess.java:63)
	at com.tom.storagemod.inventory.PlatformInventoryAccess$BlockInventoryAccess.getRootHandler(PlatformInventoryAccess.java:103)
	at com.tom.storagemod.inventory.MultiInventoryAccess.build(MultiInventoryAccess.java:52)
	at com.tom.storagemod.block.entity.InventoryConnectorBlockEntity.updateServer(InventoryConnectorBlockEntity.java:52)
	at com.tom.storagemod.util.TickerUtil.lambda$createTicker$1(TickerUtil.java:10)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:691)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:745)
	at net.minecraft.class_1937.method_18471(class_1937.java:488)

-- Block entity being ticked --
Details:
	Name: toms_storage:inventory_connector // com.tom.storagemod.block.entity.InventoryConnectorBlockEntity
	Block: Block{toms_storage:inventory_connector}
	Block location: World: (-38,-60,-10), Section: (at 10,4,6 in -3,-4,-1; chunk contains blocks -48,-64,-16 to -33,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{toms_storage:inventory_connector}
	Block location: World: (-38,-60,-10), Section: (at 10,4,6 in -3,-4,-1; chunk contains blocks -48,-64,-16 to -33,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:691)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:745)
	at net.minecraft.class_1937.method_18471(class_1937.java:488)
	at net.minecraft.class_3218.method_18765(class_3218.java:413)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['InfinityChances'/1, l='ServerLevel[Tom's Simple Storage Testing]', x=-40.78, y=-60.00, z=-11.18]]
	Chunk stats: 8281
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 59568 game time, 59568 day time
	Level name: Tom's Simple Storage Testing
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 103710 (now: false), thunder time: 76709 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 64
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Fabric Mods: 
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		badpackets: Bad Packets 0.8.1
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.102.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b55973446a
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc6a
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a76a
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c6a
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a76a
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c6a
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b36a
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b55973446a
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5b6a
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c66a
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a76a
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+1daea2156a
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae256a
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b996a
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b996a
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae066a
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd96a
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc9216a
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+780172706a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b36a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a56a
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a56a
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c6a
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b6a
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a936a
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c6a
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+650897126a
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b6a
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c6a
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c6a
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b36a
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e6a
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea2156a
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b36a
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd06a
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b16a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b55973446a
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b55973446a
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c6a
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd3436a
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea2156a
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		gammautils: Gamma Utils 1.9.20
		indium: Indium 1.0.35+mc1.21
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.1
		placeholder-api: Placeholder API 2.4.1+1.21
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		roughlyenoughitems: Roughly Enough Items 16.0.754
			error_notifier: Error Notifier 1.0.9
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		toms_storage: Tom's Simple Storage Mod 2.0.9
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-block: Cardinal Components API (blocks) 6.1.0
		wthit: wthit 12.3.0
		xaerominimap: Xaero's Minimap 24.2.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['InfinityChances'/1, l='ServerLevel[Tom's Simple Storage Testing]', x=-40.78, y=-60.00, z=-11.18]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, toms_storage
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, toms_storage, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -6302455238897095148
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.11-1.21.1
```
</details>

![image_2024-08-18_171012093](https://github.com/user-attachments/assets/fd1a969c-0d9d-472d-b6f6-63f8a0ad29c7)
Placing it is fine, but the moment I break it, the game freezes and then spits out the above error. 

I will attempt to update every mod possible and then check if that fixed it.
Edit: I updated everything, and it still crashes.

**Comment by tom5454** [comment] 2024-08-19 13:07
Duplicate of #444

**Closed by tom5454** 2024-08-19 13:07 UTC
