### ISSUE TITLE
Server Crash : Ticking block entity , Tom's v1.58, Extended Drawers v1.4.1

### ISSUE THREAD

**Issue by rxay579** [tom5454/Toms-Storage#257] opened 2023-06-28 09:40 UTC
MC v1.19.4, Fabric API v0.83.0, Tom's Simple Storage Mod v1.5.8, Extended Drawers v1.4.1

I mis-clicked and placed an Extended Drawers Compacting Drawer next to a Mythic Metals single chest that was part of an existing Tom's storage network.
The server immediately crashed and kicked out my client ; log attached.
[2023-06-28-1.log](https://github.com/tom5454/Toms-Storage/files/11892955/2023-06-28-1.log)
[crash-2023-06-28_03.02.45-server.txt](https://github.com/tom5454/Toms-Storage/files/11892454/crash-2023-06-28_03.02.45-server.txt)

I tried restarting the server instance and it crashed again upon world load.
I had a chunk loader in the storage chunk ; log attached.
[2023-06-28-2.log](https://github.com/tom5454/Toms-Storage/files/11892959/2023-06-28-2.log)
[crash-2023-06-28_03.10.51-server.txt](https://github.com/tom5454/Toms-Storage/files/11892460/crash-2023-06-28_03.10.51-server.txt)

I added "Neruina - Ticking Entity Fixer" to the server and restarted it again.
The server started, a log entry mentioned the ticking block but prevented the crash.
I logged back in, broke and picked up the inventory connector, broke and moved the compacting drawer, then replaced the inventory connector and checked the terminal; the network appeared to be intact.

I've since restarted the server again without Neruina enabled and things appear to be normal again.
I have not tried placing any regular (single, double, quad) extended drawers directly to the Tom's Simple Storage network.

I haven't had stability/crash issues with the extended drawers when connecting a tom's filtered connector to the extended drawers access point.

**Comment by rxay579** [comment] 2023-06-28 10:22
Also reported here: https://github.com/MattiDragon/ExtendedDrawers/issues/70

**Comment by rxay579** [comment] 2023-06-28 18:53
Added a minimum viable test on the Extended Drawers issue per their request.
Linked above.

**Comment by tom5454** [comment] 2023-06-29 12:41
It's Mythic Metals Decorations custom inventory handler breaking here: 
https://github.com/Noaaan/MythicMetalsDecorations/blob/1.20/src/main/java/nourl/mythicmetalsdecorations/MythicMetalsDecorations.java#L73
The `MythicChestBlock.getInventory` returns null
Duplicate of #243

**Closed by tom5454** 2023-06-29 12:41 UTC
Labels: Bug in other mod
