### ISSUE TITLE
Item duplication with belts [Create]

### ISSUE THREAD

**Issue by pknessness** [tom5454/Toms-Storage#338] opened 2024-03-27 07:43 UTC
When a belt with an item is in contact with a tom's storage, removing any item from a storage terminal will transform the belted item into the item removed, and give all items to the user.

For example, if there is a single diamond inside the Tom's Storage, and a belt with a stack of iron nuggets is connected to the Tom's Storage, a user who attempts to take out a single diamond will have in their hand a stack of diamonds, and the stack of nuggets on the belt becomes bugged.

Is there a way to blacklist items that TSS uses, such that I can simply remove belts from being viewed at all by TSS?

Am playing on Create Optimized [1.5.1f], which uses Create 1.5.1f and Tom's Simple Storage 1.6.5 on minecraft 1.20.1

**Comment by tom5454** [comment] 2024-04-07 16:18
Duplicate of #324

**Closed by tom5454** 2024-04-07 16:18 UTC
