### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WolfyZv** [tom5454/Toms-Storage#399] opened 2024-06-25 20:26 UTC
Game Version : 1.21
Mod Version : 1.21-2.0.3-fabric
Fabric 1.21

[crash-2024-06-25_22.21.24-server.txt](https://github.com/user-attachments/files/15978274/crash-2024-06-25_22.21.24-server.txt)

**Comment by tom5454** [comment] 2024-06-26 16:35
Duplicate of #398

**Closed by tom5454** 2024-06-26 16:35 UTC
