### ISSUE TITLE
Can't seem to link Wireless Terminal to my storage

### ISSUE THREAD

**Issue by katubug** [tom5454/Toms-Storage#196] opened 2023-02-15 22:37 UTC
MC: 1.19.2
Forge: 43.2.3
Mod: 1.3.10

I actually recall this being an issue in 1.18 as well - the upgraded versions would work, but the basic Wireless Terminal won't connect, regardless of whether I right click or shift right click. I'm not sure if it's a mod conflict or just something I'm doing wrong. Here's my latest.log  - 

[latest.log](https://github.com/tom5454/Toms-Storage/files/10748612/latest.log)

**Comment by tom5454** [comment] 2023-02-16 13:32
The basic wireless terminal can't bind to a block, it only extends your reach while looking at a terminal, use the advanced variant. 
Duplicate of #160

**Closed by tom5454** 2023-02-16 13:32 UTC
