### ISSUE TITLE
Can't craft storage terminal in Fabric 1.21

### ISSUE THREAD

**Issue by itsDenDen** [tom5454/Toms-Storage#388] opened 2024-06-19 20:07 UTC
For some reason the recipe is right but it doesn't show the item up at all
![image](https://github.com/tom5454/Toms-Storage/assets/67413819/4991e15e-5b82-495b-a112-7729f2f13d30)

**Comment by tom5454** [comment] 2024-06-19 20:18
Duplicate of #386
Update the mod

**Closed by tom5454** 2024-06-19 20:18 UTC
