### ISSUE TITLE
Duplication issue if this mod is paired with the Traveler's Backpack (FABRIC)

### ISSUE THREAD

**Issue by Dryadxon** [tom5454/Toms-Storage#147] opened 2022-09-07 18:52 UTC
**Steps to reproduce:**

 - Install both this mod and [Traveler's Backpack](https://github.com/Tiviacz1337/Travelers-Backpack).
 - Try to transform a backpack into a basic one using Shears in a crafting terminal.
 - The original backpack will remain in the terminal's crafting grid, a normal one, with identical content, will be crafted.

**Expected behavior:**

The original backpack should be consumed, as using any other crafting table, or equivalent block/item/entity.

**Actual behavior:**

The original backpack is kept inside the crafting grid, while a basic one is crafted.

**Comment by tom5454** [comment] 2022-09-07 20:37
Duplicate of #142

**Closed by tom5454** 2022-09-07 20:38 UTC
