### ISSUE TITLE
Craft didn't work of inventory connector & storage terminal [1.21]

### ISSUE THREAD

**Issue by Aphram-11** [tom5454/Toms-Storage#387] opened 2024-06-19 10:13 UTC
![Capture d'écran 2024-06-19 120736](https://github.com/tom5454/Toms-Storage/assets/173255181/a44336a2-0e2d-4695-8670-6cf0027fa17c)
![Capture d'écran 2024-06-19 120749](https://github.com/tom5454/Toms-Storage/assets/173255181/94ea06dd-764a-4a6c-84cb-c398e8a2b966)
![Capture d'écran 2024-06-19 121006](https://github.com/tom5454/Toms-Storage/assets/173255181/7c7b3c92-2585-4c90-bbad-f4d00c9939e7)
![Capture d'écran 2024-06-19 120948](https://github.com/tom5454/Toms-Storage/assets/173255181/4da93e6e-282f-4865-9d36-2dd953a43df1)
![Capture d'écran 2024-06-19 120900](https://github.com/tom5454/Toms-Storage/assets/173255181/7d7ea6c2-6d30-4a56-88a5-52515df9e872)
Hello, i try to play with this mods, but impossible to craft some of the blocks, like the inventory connector or the storage terminal,
I try the recipe of JEI and the one on the YT Videos, no one works.
I have only the mods jei and tom simple storage on fabric.
Have a nice day

**Comment by radek-coder** [comment] 2024-06-19 12:34
I have the same issue, the crafting recipe for the inventory connector or the storage terminal don't work and don't appear on JEI.
And the inventory cable connector is missing.

**Comment by tom5454** [comment] 2024-06-19 14:04
Duplicate of #386

**Closed by tom5454** 2024-06-19 14:04 UTC
