### ISSUE TITLE
Crash when opening the terminal

### ISSUE THREAD

**Issue by TheLucXas** [tom5454/Toms-Storage#64] opened 2021-09-23 18:12 UTC
Launcher says: "The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_342.method_1882()" because "this.searchField" is null"
Crash report: [crash-2021-09-23_15.09.17-client.txt](https://github.com/tom5454/Toms-Storage/files/7219910/crash-2021-09-23_15.09.17-client.txt)

**Comment by tom5454** [comment] 2021-09-24 16:23
Duplicate of #62

**Closed by tom5454** 2021-09-24 16:23 UTC
