### ISSUE TITLE
Feature Request: Add Item Tag Search Functionality

### ISSUE THREAD

**Issue by TDanks2000** [tom5454/Toms-Storage#327] opened 2024-02-09 20:23 UTC
Add the ability to search for item tags for example $food, $wood etc etc, just like you can in rei, jei all the other mods like that

![image](https://github.com/tom5454/Toms-Storage/assets/40835340/2f54d5aa-0c60-40b4-8754-91c1125db3bf)

**Comment by tom5454** [comment] 2024-07-20 13:37
Duplicate of #309

**Closed by tom5454** 2024-07-20 13:37 UTC
