### ISSUE TITLE
Deleted All Modded Items and Reciepe

### ISSUE THREAD

**Issue by ThasWhasUpYo** [tom5454/Toms-Storage#383] opened 2024-06-17 04:12 UTC
I'm trying to update my server I run for me and my friends and the only real mod I have is this one. I was able to update my server and it runs np, but everything from the mod is deleted. I can't craft them either. The only thing I'm capable of is /give the items but the items do not drop upon breaking. They do seem to have their functionality, but I am seeing barrier blocks appear in my systems can't grab them though.

Upon joining the server for the first time, the console spits out
Invalid statistic in .\world\stats\3d0d4fdf-570d-4abf-8b2d-04c53610859e.json: Don't know what toms_storage:ts.inventory_cable_connector is

And

Tried to load unrecognized recipe: toms_storage:trim removed now.

And it did think for every recipe and item deleting them from my world and don't have access to them without cheating

**Comment by Mason-931** [comment] 2024-06-17 19:20
Yeah it also doesn't even let you pair the advanced wireless terminal to your system. I updated my pre-existing world but can't re-pair it. Now i have to go to my storage system to use it :( First World Problems, huh?

**Comment by tom5454** [comment] 2024-06-18 13:35
The 1.21 version is a major rewrite, so the block ids, and their functions changed. (There won't be a filtered inventory cable connector, the regular connector will have filtering, all of the painted blocks work completly differently on fabric, removing many duplicate blocks).
I released a patch for the recipe and terminal issue.
Duplicate of #380 and #382

**Closed by tom5454** 2024-06-18 13:35 UTC
