### ISSUE TITLE
1.21 Filters

### ISSUE THREAD

**Issue by IllegallyBlind1** [tom5454/Toms-Storage#416] opened 2024-07-16 03:54 UTC
Filters straight up don't work when used in more than 1 chest and there's zero up to date guides to use the configurator or filters.

**Comment by Gharsnull** [comment] 2024-07-17 00:57
+1 https://github.com/tom5454/Toms-Storage/issues/414

**Comment by tom5454** [comment] 2024-07-17 13:05
Duplicate of #414

**Closed by tom5454** 2024-07-17 13:05 UTC
